language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

    # For the emulator
    - sys-img-armeabi-v7a-android-19

jdk: oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script: ./gradlew build connectedCheck
